name: ApiOpsDeploy

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      environments:
        description: 'environment to deploy to'
        required: true
        type: environment

permissions:
  id-token: write
  contents: write

env:
  RUNNER_DEBUG: 1

jobs:
  # This workflow contains a single job called "build"
  deploy-apis:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    env:
      SP_APPID: ${{secrets.APPID}}
      SP_PASSWORD: ${{secrets.PASSWORD}}
      SP_TENANT: ${{secrets.TENANT}}

    steps:
      - uses: actions/checkout@v4

      - name: Set PSCredential Object
        run: |
          Write-Host "input: ${{inputs.environment}}"
          Write-Host "environment: ${{vars.env}}"
        shell: pwsh
